version: "3"
services:

  ui:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: work-clock-ui
    image: work-clock-ui
    networks:
      - work-clock-net
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - ./src:/usr/app/src 
      - /usr/app/node_modules
    expose:
      - 3000

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    container_name: work-clock-api
    image: work-clock-api
    networks:
      - work-clock-net
    volumes:
      - type: bind
        source: ./backend
        target: /usr/server
      - /usr/server/node_modules
    env_file:
    - ./backend/.env
    expose:
      - 5000

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: work-clock-db
    networks:
      - work-clock-net
    volumes:
      - mongo-data:/data/db

networks:
  work-clock-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    
  
