# The name of the workflow.
name: Build and Deploy Work-Clock

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - master

# Set environment variables
env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: self-hosted
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies and run tests for the client application
      - name: Install and Test client
        working-directory: ./
        run: |
          npm install
          npm run build

      # Build a Docker image for the client application
      - name: Build Client Docker Image
        working-directory: ./
        # Build image with tag rakeshpotnuru/productivity-app:client
        run: |
          docker build -t amit&karun/work-clock:client-${{github.run_number}} .

      # Login to Docker Hub using credentials from repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push amit&karun/work-clock:client-${{github.run_number}}

# other pipeline with docker-compose.yaml -----------------------------------------------------------

# # The name of the workflow.
# name: Build and Deploy Work-Clock

# # Run the workflow when code is pushed to the main branch
# on:
#   push:
#     branches:
#       - master

# # Set environment variables
# env:
#   # MONGODB_URI: ${{ secrets.MONGODB_URI }}
#   # TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
#   # EMAIL: ${{ secrets.EMAIL }}
#   # PASSWORD: ${{ secrets.PASSWORD }}
#   NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

# # This is the workflow that is being run.
# jobs:
#   build-and-deploy:
#     # This is telling GitHub to run the workflow on the latest version of Ubuntu.
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout the code from the GitHub repository
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Install dependencies and run tests for the client application
#       - name: Install and Test client
#         working-directory: ./
#         run: |
#           npm install
#           npm run dev

#       # Replace the Docker build and push steps with Docker Compose
#       - name: Deploy with Docker Compose
#         run: docker-compose up -d